### ISSUE TITLE
Error during install (readme.md missing info?)

### ISSUE THREAD

**Issue by pihentagy** [conversence/idealoom#2]
During [install](https://github.com/conversence/idealoom/blob/develop/doc/INSTALL.rst#check-out-the-code-repository-install-build-dependencies-and-bootstrap) I get the following:
```
$ fab env_dev install_single_server
/usr/lib/python2.7/dist-packages/Crypto/Cipher/blockalgo.py:141: FutureWarning: CTR mode needs counter parameter, not IV
  self._cipher = factory.new(key, *args, **kwargs)
[localhost] Login password for '****': 
```

What am I supposed to type as password? It does not accept empty string, and does not accept anything else.

**Comment by maparent** [comment]
Hello, and welcome! The fab command does a ssh into the target host, in this case localhost. This is the same password you'd enter if you  were doing ssh localhost, which is your user's password. You can avoid this step if you have a public-private key for yourself in ~/.ssh, and the public key is in ~/.ssh/authorized_keys. (You may also have to set up ssh-agent.) Tell me if you need more details.

**Comment by maparent** [comment]
Added a comment in INSTALL.rst as suggested, reopen if you feel it's unclear. Cheers!
